### ISSUE TITLE
Images are hidden in RSS feed

### ISSUE THREAD

**Issue by Crocmagnon** [bradleytaunt/phpetite#1]
Coming from your blog to report this 😊✌🏻

Current behavior:
When I read an article in my RSS feed reader (miniflux), the images appear with the « click to load image ». I have to click on « view full size image » to view the image.

Expected behavior:
Images are properly rendered in the RSS feed, no need to click on anything to get them.

**Comment by Crocmagnon** [comment]
Also, just curious: wouldn’t [lazy loading](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) work for your use case?

**Comment by bradleytaunt** [comment]
@Crocmagnon You are absolutely correct. I definitely overlooked the RSS users in this aspect.

I have since updated my person PHPetite blog to no longer do this, and mentioned you in an update to the "Clock to Load Images" article: https://uglyduck.ca/#2021-03-25-load-image-on-click

Cheers!

**Comment by Crocmagnon** [comment]
Thanks ! 😃
